def gensalt(rounds: int = 12, prefix: bytes = b"2b") -> bytes: ...
def hashpw(password: bytes, salt: bytes) -> bytes: ...
def checkpw(password: bytes, hashed_password: bytes) -> bool: ...
def kdf(
    password: bytes,
    salt: bytes,
    rounds: int,
    desired_key_bytes: int,
    ignore_few_rounds: bool = False,
) -> bytes: ...
